services:
  app:
    container_name: spring-boot-app
    image: airport-gate-management-app
    ports:
      - "8181:8181"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/app_db
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop

  db:
    container_name: db
    image: postgres:17
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres:

networks:
  app-network:
    driver: bridge